resources:
- name: steph-node-app
  type: git
  source:
    uri: https://github.com/L8dySneaks/node.git
    branch: master
- name: steph-node-demo-cf
  type: cf
  source:
    api: https://api.sys.gn01.pcf.dcsg.com
    username: ((cf_user_nonprod))
    password: ((cf_password_nonprod))
    organization: bazaz-demo
    space: dev
    skip_cert_check: true

jobs:
- name: steph-deploy
  plan:
  - get: steph-node-app
    trigger: true
  - put: steph-node-demo-cf
    params:
      manifest: steph-node-app/manifest.yml
      path: steph-node-app/
